### ISSUE TITLE
Autocompletion in yaml file

### ISSUE THREAD

**Issue by shmygol** [PinkFloyded/idea-file-path-autocomplete#10]
Is the plugin supposed to work in Yaml files?

Steps:
1. Install YAML-plugin
2. Open file test.yml
3. Try to input `service: /tm`

Actual result:
Autocomplete is not invoked even by tab.

**Comment by PinkFloyded** [comment]
The logic right now is that it autocompletes only inside quotes. Adding support for languages where a path outside a quote might make sense. yaml, makefile and shell scripts come to mind.

**Comment by PinkFloyded** [comment]
Hi, as of `0.4.0` completion should be working on YAML files.
