### ISSUE TITLE
Remote SSH Interpreter

### ISSUE THREAD

**Issue by AndyP103** [PinkFloyded/idea-file-path-autocomplete#11]
I'm running PyCharm on a windows machine, setup with a remote SSH interpreter on a Linux server.  Autocomplete runs for local windows folder structure, starting with '\'; however, all files will be run on the remote Linux machine and should use that folder structure and have autocomplete start with '/'

**Comment by PinkFloyded** [comment]
Hi Andy, this might be very hard to implement as essentially the file path details need to be fetched from the interpreter that's been configured. This interpreter can be Python or PHP or anything else. Also, the intellij plugin SDK needs to provide a means to achieve this which I'm not sure it does. I think this is a very rare use-case to warrant this effort.
