### ISSUE TITLE
Paths complete with backslash on Windows 10

### ISSUE THREAD

**Issue by patrickspry** [PinkFloyded/idea-file-path-autocomplete#12]
I'm using PyCharm 2019.2 on Windows 10. Seems like relative paths work fine with forward slash (e.g. starting with "./" or "../" plus `Ctrl + Space`), but if I enter `'C:/'` no suggestions come up. If I use backslashes, e.g. `'C:\'` this will work for autocompletion, but the resulting string is inappropriate for python (`\` is an escape character). The desired behavior would be to have `C:/` produce the appropriate suggestions, and new directories would complete with an additional `/`

PyCharm 2019.2 (Professional Edition)
Build #PY-192.5728.105, built on July 23, 2019
Runtime version: 11.0.3+12-b304.10 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1949M
Cores: 8
Registry: 
Non-Bundled Plugins: CMD Support, com.pinkfloyded.idea-file-path-autocomplete.idea-file-path-autocomplete

**Comment by PinkFloyded** [comment]
Hi Patrick, thanks for the report. This issue is fixed in 0.4.1. Please try it out.
